# Copyright (c) 2024 Microsoft Corporation.
# Licensed under the MIT License

"""Persona, entity type, relationships and domain generation prompts module."""

from .community_reporter_role import GENERATE_COMMUNITY_REPORTER_ROLE_PROMPT_ZH
from .domain import GENERATE_DOMAIN_PROMPT_ZH
from .entity_relationship import (
    ENTITY_RELATIONSHIPS_GENERATION_JSON_PROMPT_ZH,
    ENTITY_RELATIONSHIPS_GENERATION_PROMPT_ZH,
    UNTYPED_ENTITY_RELATIONSHIPS_GENERATION_PROMPT_ZH,
)
from .entity_types import (
    ENTITY_TYPE_GENERATION_JSON_PROMPT_ZH,
    ENTITY_TYPE_GENERATION_PROMPT_ZH,
)
from .persona import GENERATE_PERSONA_PROMPT_ZH

__all__ = [
    "ENTITY_RELATIONSHIPS_GENERATION_JSON_PROMPT_ZH",
    "ENTITY_RELATIONSHIPS_GENERATION_PROMPT_ZH",
    "ENTITY_TYPE_GENERATION_JSON_PROMPT_ZH",
    "ENTITY_TYPE_GENERATION_PROMPT_ZH",
    "GENERATE_COMMUNITY_REPORTER_ROLE_PROMPT_ZH",
    "GENERATE_DOMAIN_PROMPT_ZH",
    "GENERATE_PERSONA_PROMPT_ZH",
    "UNTYPED_ENTITY_RELATIONSHIPS_GENERATION_PROMPT_ZH",
]
